#   Copyright (c)  2020, CardioPipeLine
#   Author: Rohit Suratekar
#   Organization: IIMCB
#
# All path and filename resolver

import os
import shutil

from constants.genomics import *
from constants.system import *
from constants.tools import *


class PathUtil:
    def __init__(self):
        self.data = DEX_DATA
        self.prefetch = f"{TOOL_SRA}/prefetch"
        self.fasterq_dump = f"{TOOL_SRA}/fasterq-dump"
        self._ncbi_sra = f"{FOLDER_NCBI_PUBLIC}/sra"
        self.sra_accession = SRA_ACCESSION
        self.star = f"{TOOL_STAR}/STAR"
        self.genome_fasta = ZEBRAFISH_GENOME_FASTA
        self.gtf_annotation = ZEBRAFISH_GTF_ANNOTATION
        self.sortmerna = f"{TOOL_SORT_ME_RNA}/sortmerna"
        self.rrna_db = RRNA_DATABASE

    @property
    def sra_db(self):
        """
        :return: full path of the base folder of local SRA database
        """
        return f"{self.data}/sra"

    @property
    def star_index(self):
        """
        :return: full path of STAR index folder
        """
        return f"{DEX_WORK}/Genome/index/star"

    @property
    def sortmerna_index(self):
        """
        :return: full path of sortmerna index folder
        """
        return f"{DEX_WORK}/Genome/index/sortmerna"

    def sra_meta(self, sra_id: str) -> str:
        """
        :param sra_id: SRA id
        :return: full path of metadata file of given SRA id
        """
        return f"{self.sra_db}/{sra_id}/{sra_id}_meta.json"

    @staticmethod
    def exists(path: str) -> bool:
        """Checks if given path exists
        :param path: full path
        :return: True if path exists
        """
        return os.path.exists(path)

    def sra_meta_exists(self, sra_id: str) -> bool:
        """
        Check if metadata file is present in the SRA folder

        This metadata file is generated by the CardioPipeLine package from
        the SRA_Annotation.tab file. It contains the relationship between
        given SRA id (experiment id) and the SRR id (run id). It also
        contains other metadata generated by this package as well as derived
        from the annotation file.
        :param sra_id: SRA id
        :return: returns True if metadata file exist for given SRA id
        """
        return self.exists(self.sra_meta(sra_id))

    def srr(self, sra_id: str, srr_id: str) -> str:
        """
        Generate name of the sra file of the given SRA id and its run id
        :param sra_id: SRA id (experiment id)
        :param srr_id: SRR id (run id)
        :return: full path of the run.sra file
        """
        return f"{self.sra_db}/{sra_id}/{srr_id}.sra"

    def srr_exists(self, sra_id: str, srr_id: str) -> bool:
        """Checks if given sra file is available for given SRA id and SRR id
        :param sra_id: SRA id (experiment id)
        :param srr_id: SSR id (run id)
        :return:
        """
        return self.exists(self.srr(sra_id, srr_id))

    def ncbi_srr(self, srr_id: str) -> str:
        """
        :param srr_id: SRR id
        :return: default path of the downloaded file in temporary NCBI
        public folder
        """
        return f"{self._ncbi_sra}/{srr_id}.sra"

    def fastq(self, sra_id) -> list:
        """
        :param sra_id: SRA id
        :return: List of all available fastq files in the folder of given
        SRA id
        """
        all_files = []
        for f in os.listdir(f"{self.sra_db}/{sra_id}"):
            if f.endswith(".fastq"):
                all_files.append(f"{self.sra_db}/{sra_id}/{f}")
        return all_files

    def fastq_dir(self, sra_id) -> str:
        """
        :param sra_id: SRA id
        :return: Path of fastq files of given SRA id
        """
        return f"{self.sra_db}/{sra_id}"

    def star_bam_prefix(self, sra_id: str):
        return f"{self.sra_db}/{sra_id}/{sra_id}_"

    def make_sra_path(self, sra_id: str):
        """Makes folder for given SRA id

        :param sra_id: SRA id
        """
        target = f"{self.sra_db}/{sra_id}"
        if not self.exists(target):
            os.makedirs(target)

    def make(self, path: str):
        """ Makes dir structure of given path

        :param path: Path of the dictionary
        """
        if not self.exists(path):
            os.makedirs(path)

    @staticmethod
    def remove_all(path):
        """ Removes everything at this path (including sub-folders and files)
        :param path: Full path to delete
        """
        if os.path.isfile(path):
            os.remove(path)
        else:
            shutil.rmtree(path)
