# Test file to run R scripts from the RStudio to debug them

# Combined analysis of DESeq2

library("jsonlite") # To read the json file (configuration file)

source("rscripts/functions.R")


# Get the configuration file generated by the python script and use its path.
# For this test, I have copy pasted this file from its original path to the root of the project

data <- jsonlite::fromJSON("star.config.json", flatten = TRUE)

raw_counts <- as.data.frame(read_csv("star.counts.csv"))
rownames(raw_counts) <- raw_counts$gene_id
counts <- raw_counts[order(raw_counts$gene_id),]
counts$gene_id <- NULL
dds <- DESeq2::DESeq(dds)
res <- DESeq2::results(dds, contrast = data$contrast, alpha = data$alpha)
print(head(counts))
