"""
CardioPipeLine (c) 2020

Author: Rohit Suratekar, ZDG Lab, IIMCB

This deals with all constants
"""

TASK_ALL = 0
TASK_DOWNLOAD = 1
TASK_CONVERT_FASTQ = 2
TASK_FILTER_RRNA = 3
TASK_STAR_INDEX = 4
TASK_STAR_MAPPING = 5
TASK_STRINGTIE = 6
TASK_SALMON_INDEX = 7
TASK_SALMON_MAPPING = 8
TASK_KALLISTO_INDEX = 9
TASK_KALLISTO_MAPPING = 10
TASK_COUNT_STRINGTIE = 11
TASK_COUNT_STAR = 12
TASK_COUNT_SALMON = 13
TASK_COUNT_KALLISTO = 14
TASK_DESEQ = 15
TASK_MULTI_QC = 16
