"""
CardioPipeLine (c) 2020

Author: Rohit Suratekar, ZDG Lab, IIMCB

This deals with all constants
"""

TASK_ALL = 0
TASK_DOWNLOAD = 1
TASK_CONVERT_FASTQ = 2
TASK_FILTER_RRNA = 3
TASK_STAR_INDEX = 4
TASK_STAR_MAPPING = 5
TASK_STRINGTIE = 6
TASK_SALMON_INDEX = 7
TASK_SALMON_MAPPING = 8
TASK_KALLISTO_INDEX = 9
TASK_KALLISTO_MAPPING = 10
TASK_COUNT_STRINGTIE = 11
TASK_COUNT_RSUB = 12
TASK_COUNT_TXI = 13
TASK_DESEQ = 14
TASK_CLEAN_UP = 15
